export type EmojiEntry = { emoji: string; name: string; keywords: string[]; };

// A small curated list (not a full emoji database/dependency - matches the playground's own
// approach of a self-authored list, just narrower) covering the categories most likely to show up
// in a product description: reactions, common gestures, shipping/commerce, and a handful of
// symbols/objects.
export const EMOJI_LIST: EmojiEntry[] = [
  { emoji: "😀", name: "grinning face", keywords: ["smile", "happy"] },
  { emoji: "😃", name: "grinning face with big eyes", keywords: ["smile", "happy"] },
  { emoji: "😄", name: "grinning face with smiling eyes", keywords: ["smile", "happy", "joy"] },
  { emoji: "😁", name: "beaming face", keywords: ["smile", "happy", "grin"] },
  { emoji: "😆", name: "grinning squinting face", keywords: ["laugh", "happy"] },
  { emoji: "😊", name: "smiling face with smiling eyes", keywords: ["smile", "happy", "blush"] },
  { emoji: "🙂", name: "slightly smiling face", keywords: ["smile"] },
  { emoji: "😉", name: "winking face", keywords: ["wink"] },
  { emoji: "😍", name: "heart eyes", keywords: ["love", "heart"] },
  { emoji: "😘", name: "face blowing a kiss", keywords: ["kiss", "love"] },
  { emoji: "😎", name: "smiling face with sunglasses", keywords: ["cool"] },
  { emoji: "🤔", name: "thinking face", keywords: ["think", "hmm"] },
  { emoji: "😅", name: "grinning face with sweat", keywords: ["relief", "phew"] },
  { emoji: "😂", name: "face with tears of joy", keywords: ["laugh", "lol"] },
  { emoji: "🙁", name: "slightly frowning face", keywords: ["sad", "frown"] },
  { emoji: "😢", name: "crying face", keywords: ["sad", "cry"] },
  { emoji: "😮", name: "face with open mouth", keywords: ["wow", "surprise"] },
  { emoji: "😴", name: "sleeping face", keywords: ["sleep", "tired"] },
  { emoji: "😇", name: "smiling face with halo", keywords: ["angel", "innocent"] },
  { emoji: "🥳", name: "partying face", keywords: ["party", "celebrate"] },
  { emoji: "👍", name: "thumbs up", keywords: ["like", "yes", "approve"] },
  { emoji: "👎", name: "thumbs down", keywords: ["dislike", "no"] },
  { emoji: "👏", name: "clapping hands", keywords: ["clap", "applause", "congrats"] },
  { emoji: "🙌", name: "raising hands", keywords: ["celebrate", "yay"] },
  { emoji: "🙏", name: "folded hands", keywords: ["please", "thanks", "pray"] },
  { emoji: "👌", name: "OK hand", keywords: ["ok", "perfect"] },
  { emoji: "✌️", name: "victory hand", keywords: ["peace"] },
  { emoji: "💪", name: "flexed biceps", keywords: ["strong", "muscle"] },
  { emoji: "👋", name: "waving hand", keywords: ["wave", "hello", "bye"] },
  { emoji: "🤝", name: "handshake", keywords: ["deal", "agreement"] },
  { emoji: "❤️", name: "red heart", keywords: ["love", "heart"] },
  { emoji: "⭐", name: "star", keywords: ["star", "favorite", "rating"] },
  { emoji: "🌟", name: "glowing star", keywords: ["star", "sparkle"] },
  { emoji: "🔥", name: "fire", keywords: ["hot", "trending"] },
  { emoji: "✨", name: "sparkles", keywords: ["sparkle", "new", "shiny"] },
  { emoji: "🎉", name: "party popper", keywords: ["celebrate", "congrats"] },
  { emoji: "🎁", name: "wrapped gift", keywords: ["gift", "present"] },
  { emoji: "📦", name: "package", keywords: ["box", "shipping", "delivery"] },
  { emoji: "🚚", name: "delivery truck", keywords: ["shipping", "delivery"] },
  { emoji: "🛒", name: "shopping cart", keywords: ["cart", "shopping", "buy"] },
  { emoji: "💰", name: "money bag", keywords: ["money", "price", "sale"] },
  { emoji: "💳", name: "credit card", keywords: ["payment", "card"] },
  { emoji: "🏷️", name: "label", keywords: ["tag", "price", "sale"] },
  { emoji: "✅", name: "check mark", keywords: ["done", "check", "yes"] },
  { emoji: "❌", name: "cross mark", keywords: ["no", "wrong", "cancel"] },
  { emoji: "⚠️", name: "warning", keywords: ["warning", "caution", "alert"] },
  { emoji: "❓", name: "question mark", keywords: ["question", "help"] },
  { emoji: "❗", name: "exclamation mark", keywords: ["important", "alert"] },
  { emoji: "💡", name: "light bulb", keywords: ["idea", "tip"] },
  { emoji: "📌", name: "pushpin", keywords: ["pin", "note"] },
  { emoji: "📝", name: "memo", keywords: ["note", "write"] },
  { emoji: "🔒", name: "locked", keywords: ["lock", "secure", "private"] },
  { emoji: "🔓", name: "unlocked", keywords: ["unlock", "open"] },
  { emoji: "📷", name: "camera", keywords: ["photo", "picture"] },
  { emoji: "🎨", name: "artist palette", keywords: ["design", "art", "color"] },
  { emoji: "🚀", name: "rocket", keywords: ["fast", "launch"] },
  { emoji: "🌍", name: "globe", keywords: ["world", "global"] },
  { emoji: "☀️", name: "sun", keywords: ["sunny", "weather"] },
  { emoji: "🌈", name: "rainbow", keywords: ["colorful"] },
];
